spring.datasource.url=jdbc:mysql://localhost:3306/olimpiadaSpring
spring.datasource.username=root
spring.datasource.password=


# Configuraciones de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true