spring.datasource.url=jdbc:mysql://localhost:3306/olimpiadas
spring.datasource.username=root
spring.datasource.password=
#Forzar json
spring.mvc.converters.preferred-json-mapper=jackson
spring.jackson.serialization.fail-on-empty-beans=false


# Configuraciones de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

